language: python
python:
  - "3.5"
  - "3.6"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
script:
  - make unittests
after_success:
  - coveralls